projekty/django_components/books/urls.py
from django.urls import path
from .views import book_lists, book_details

app_name = "books"
urlpatterns = [
    path('', book_lists, name="list"),
    path('<int:id>/', book_details, name="details"),
]

projekty/django_components/django_components/urls.py
from django.contrib import admin
from django.urls import path, include

from django.http import HttpResponse


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("examples/", include("examples.urls")),   # http://127.0.0.1/components/
    path("examples2/", include("examples2.urls")),   
    path("books/", include("books.urls")),

] 

projekty/django_components/examples/urls.py
from django.urls import path

from .views import list_view, details_view

app_name = "examples"
urlpatterns = [
    path("", list_view, name="list"),  # http://127.0.0.1/components/
    path("<element>/", details_view, name="details"),  # http://127.0.0.1/components/<element>/
]

projekty/django_components/examples2/urls.py
from django.urls import path

from .views import first_view, details_view

app_name = "examples2"
urlpatterns = [
    path("", first_view, name="list"),  # http://127.0.0.1/examples2/
    path("<element>/", details_view, name="details"),  # http://127.0.0.1/examples2/<element>/
]

projekty/django_components/home/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index'),
]   

projekty/django_components/books/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    description = models.TextField()
    pages = models.IntegerField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

projekty/django_components/examples/models.py
# Create your models here.

projekty/django_components/examples2/models.py
# Create your models here.

projekty/django_components/home/models.py
# Create your models here.

projekty/django_components/books/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Book
# Create your views here.

@login_required
def book_lists(request):

    books = Book.objects.all()

    # konkretna ksiazka
    
    return render(request, "books/list.html", {"books": books})


@login_required
def book_details(request, id):
    book = Book.objects.get(id=id)
    return render(request, "books/details.html", {"book": book})

projekty/django_components/examples/views.py
from django.shortcuts import render



# Create your views here.
def list_view(request):
    return render(request, "examples/list.html", {"elementy": ["a", "b", "c"]})


def details_view(request, element):
    return render(request, "examples/details.html", {"element": element})


"""
templates/
    y.html
    examples/
        x.html
    examples2/
        x2.html
        x3.html


"""


""""""

projekty/django_components/examples2/views.py
from django.shortcuts import render

# Create your views here.
def first_view(request):
    elementy = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]

    #             
    return render(
        request=request, 
        template_name="examples2/list.html", 
        context={"elementy": elementy}
    )

# argumenty są przekazywane z urls.py
# nazwy argumentów funkcji muszą być takie same jak w urls.py
def details_view(request, element):
    return render(
        request=request, 
        template_name="examples2/details.html", 
        context={"element": element}
    )

projekty/django_components/home/views.py
from django.shortcuts import render
from datetime import datetime
# Create your views here.


class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"Person(name={self.name}, age={self.age})"

    @property
    def rok_urodzenia(self):
        return datetime.now().year - self.age

    def tabelka(self):
        return f"<table class='table'><tr><td>{self.name}</td><td>{self.age}</td></tr></table>"


def jakas_funkcja():
    return "jakaś funkcja"

def funkcja_z_parametrami(a, b):
    return f"a={a}, b={b}"

def index(request):
    print("GET", request.GET)
    print("POST", request.POST)

    if request.GET.get("a"):
        print("a", request.GET.get("a"))
        print("a", request.GET.get("a"))

    person = Person("Jan", 30)
    return render(
        request, 
        'home/index.html', 
        {
            "text": "Mogę przekazać tekst do szablonu",
            "lista": ["a", "b", "c"],
            "tuple": ("a1", "b2", "c3"),
            "dict": {"a": "a1", "b": "b2", "c": "c3"},

            "number": 1234567890,
            "number2": 1234567890.1234567890,
            "number3": 1234567890.1234567890,
            "number4": 1234567890.1234567890,

            "date": datetime.now(),

            "person": person,

            "funkcja": jakas_funkcja,
            "funkcja_z_parametrami": funkcja_z_parametrami,
        })

projekty/django_components/books/templates/books/details.html
{% extends "base.html" %}

{% block content %}
<h1>Book Details</h1>
<p>{{ book.title }}</p>
<p>{{ book.author }}</p>
<p>{{ book.description }}</p>
<p>{{ book.pages }}</p>
<p>{{ book.price }}</p>
{% endblock %}

projekty/django_components/books/templates/books/list.html
{% extends "base.html" %}

{% block content %}
<h1>Books</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Description</th>
            <th>Pages</th>
            <th>Price</th>
        </tr>
    </thead>
{% for book in books %}
    <tr>
        <td><a href="{% url 'books:details' book.id %}">{{ book.title }}</a></td>
        <td>{{ book.author }}</td>
        <td>{{ book.description }}</td>
        <td>{{ book.pages }}</td>
        <td>{{ book.price }}</td>
    </tr>
{% endfor %}
</table>
{% endblock %}

projekty/django_components/examples/templates/y.html
Jestem sobie Y.html

projekty/django_components/examples2/templates/examples2/details.html
{% extends "base.html" %}

{% block content %}

jestem details.html


<p>
    szczegóły elementu {{ element }}
</p>

{% endblock %}

projekty/django_components/examples2/templates/examples2/list.html
{% extends "base.html" %}

{% block content %}


<h1>jestem X.html - wyświetlam jakas listę elementów</h1>


{% comment %} {{ elementy }} {% endcomment %}
<br>
<a href="{% url 'examples2:details' 'przyklad' %}">Link do details dla zmiennej przyklad</a>
<br>

<ul>
{% for element in elementy %}
    <li><a href="{% url 'examples2:details' element %}">{{ element }}</a></li>
{% endfor %}
</ul>

{% endblock %}

projekty/django_components/home/templates/home/index.html
{% extends "base.html" %}

{% block content %}

<p>
{{ text|upper }}  <!-- użycie filtra upper -->
</p>

<p>
    {{ lista }}  <br>
    {{ lista|first }}

    {% for element in lista %}{{element}}<br>{% endfor %}

</p>

<p>
    {{ tuple }}  <br>
    {{ tuple|first }}<br>
    {% for element in tuple %}{{element}}<br>{% endfor %}<br>
    
    wybieranie po indeksie: <br>
    {{ tuple.0 }}

</p>

<p>
    {{ dict }}  <br>
    {{ dict.a }} <br>
    {% for key, value in dict.items %}
        {{ key }} - {{ value }}<br>
    {% endfor %}
</p>

<p>
    {{ number }}  <br>
    {{ number|floatformat:2 }}  <br>
    {{ number|floatformat:0 }}  <br>
    {{ number2|floatformat:1 }}  <br>
    {{ number|floatformat:3 }}  <br>

</p>

<p>
    {{ date }}  <br>
    {{ date|date:"d-m-Y" }}  <br>
    
    {{ date|date:"d.m.Y H:i:s" }}  <br>
</p>

<p>
    {{ person }}  <br>
    {{ person.name }}  <br>
    {{ person.age }}  <br>
    {{ person.rok_urodzenia }}  <br>
    {{ person.tabelka }}  <br>
    {{ person.tabelka|safe }}  <br>
</p>


<p>
    {{ funkcja }}  <br>

</p>

<p>
{% lorem 10 p random %}
</p>

{% endblock %}

projekty/django_components/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    
    <div class="container">
    {% include "includes/header.html" %}

    {% block content %}
    {% endblock %}
    
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>